services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=BlogDB #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    
  esdb-node:
    image: ghcr.io/eventstore/eventstore:20.6.1-alpha.0.69-arm64v8
    container_name: esdb-node
    ports:
      - "2113:2113"
      - "1113:1113"
    command:
      - "--insecure"
      - "--run-projections=All"
      - "--enable-external-tcp"
      - "--enable-atom-pub-over-http"
    stdin_open: true
    tty: true  
